#!/bin/bash
#
# Copyright 2020 Vincente <vincenteliang@foxmail.com>
# Copyright 2020-2021 Jason <jason23347@163.com>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.

# rcv cmd args from cli
command=$1
name=$2
loc=$3

# 1 to turn on debug mode, redirect log stream to stderr
DEBUG=0
# Randomly delay report submission for 0-${MAX_DELAY_REPORT} minutes
MAX_DELAY_REPORT=20
MAX_DELAY_PING=5
MAX_RETRY=5

# host
REPORT_HOST=https://isport.ustb.edu.cn

# path settings
BASE_DIR="/volume1/docker/hass/ustb-daily-report/"
WWW_DIR="/volume1/mount/home/www/ustb-log"
DATA_DIR="$BASE_DIR/data"
LOG_DIR="$BASE_DIR/log"
LOG_FILE="$LOG_DIR/$name.log"
PING_RET="$BASE_DIR/ping/$name.ping"
REPORT_RET="$BASE_DIR/report/$name.report"

# customized data
REPORT_COOKIE="$(cat $DATA_DIR/$name-$loc/REPORT-COOKIE)"
REPORT_DATA="$(cat $DATA_DIR/$name-$loc/REPORT-DATA)"
REPORT_UA="$(cat $DATA_DIR/$name-$loc/REPORT-UA)"

# Using mutt by default,
# change to sendmail if you like
send_alert() {
        echo "UNDERCONSTURCTION"
}

if [ $DEBUG -eq 0 ]; then
        RETRY_FREQUENCY=20 # seconds
        RANDOM_DELAY=1
else
        RETRY_FREQUENCY=2
        RANDOM_DELAY=0
fi

write_log() {
        printf "[%s][%s] %s\n" "$(date +"%Y-%m-%d %H:%M:%S")" "$command $name $loc" "$1" | tee -a $LOG_FILE
        rsync -az $LOG_FILE $WWW_DIR/
}

report() {
        curl -k -L \
                -X POST "$REPORT_HOST/app.RSPWxClient/index.jsp"  \
                -H "Host: isport.ustb.edu.cn"  \
                -H "Accept: */*"  \
                -H "Connection: keep-alive"  \
                -H "X-Requested-With: XMLHttpRequest"  \
                -H "User-Agent: $REPORT_UA"  \
                -H "Content-Type: application/x-www-form-urlencoded; charset=UTF-8"  \
                -H "Origin: $REPORT_HOST"  \
                -H "Referer: $REPORT_HOST/app.RSPWxClient/index.jsp?m=yqinfo&c=index&a=init"  \
                -H "Accept-Language: zh-CN,zh;q=0.9,en-US;q=0.8,en;q=0.7"  \
                -H "Cookie: $REPORT_COOKIE" \
                --data "$REPORT_DATA"  \
                --compressed \
                -o $REPORT_RET
        
        # deal with return, known situation
        grep 'Submission succeed' $REPORT_RET >/dev/null && return 0
        grep 'You have submitted today' $REPORT_RET >/dev/null && return 1
        grep 'succeed_m_l' $REPORT_RET >/dev/null && return 2

        # deal with unknown situation
        REPORT_ERR_LOG=$REPORT_RET.FAILED.$(date +"%Y-%m-%d-%H-%M-%S")
        cp $REPORT_RET $REPORT_ERR_LOG
        write_log "Unknown error with return $REPORT_ERR_LOG"
        return -1
}

ping(){
        # get return
        curl -skL \
        -X GET "$REPORT_HOST/app.RSPWxClient/index.jsp?m=yqinfo&c=index&a=init" \
        -H "User-Agent: $REPORT_UA"  \
        -H "Cookie: $REPORT_COOKIE" \
        -H "X-Requested-With: XMLHttpRequest" \
        -o $PING_RET

        # deal with return, known situation
        grep 'drtw' $PING_RET >/dev/null && return 0
        grep '!isWeixin' $PING_RET >/dev/null && return 1
        
        # deal with unknown situation
        PING_ERR_LOG=$PING_RET.FAILED.$(date +"%Y-%m-%d-%H-%M-%S")
        cp $PING_RET $PING_ERR_LOG
        write_log "Unknown error with return $PING_ERR_LOG"
        return -1
}

case $command in
report)
        if [ ${RANDOM_DELAY:-0} -eq 1 ]; then
                rnd=$((RANDOM % $MAX_DELAY_REPORT))
                delay=$(($rnd * 60))
                write_log "Random delay for $rnd minutes."
                sleep $delay
        fi
        declare -i n=0
        while [ $n -lt $MAX_RETRY ]; do
                report
                [ $? -eq 0 ] && write_log "Succeed." && break
                [ $? -eq 1 ] && write_log "Redundant Report." && break
                [ $? -eq 2 ] && write_log "Seession Expired." && ((n+=1))
                [ $? -eq -1 ] && write_log "Unknown Error." && ((n+=1))
                # send alert after maximun retry
                [ $n -ge $MAX_RETRY ] && send_alert && exit 1
                write_log "Retrying in ${RETRY_FREQUENCY}(s)."
                sleep $RETRY_FREQUENCY
        done
        ;;
ping)
        declare -i n=0
        if [ ${RANDOM_DELAY:-0} -eq 1 ]; then
                rnd=$((RANDOM % $MAX_DELAY_PING))
                delay=$(($rnd * 60))
                write_log "Random delay for $rnd minutes."
                sleep $delay
        fi
        while [ $n -lt $MAX_RETRY ]; do
                ping
                [ $? -eq 0 ] && write_log "Succeed." && break
                [ $? -eq 1 ] && write_log "Seession Expired." && ((n+=1))
                [ $? -eq -1 ] && write_log "Unknown Error." && ((n+=1))
                # send alert after maximun retry
                [ $n -ge $MAX_RETRY ] && send_alert && exit 1
                write_log "Retrying in ${RETRY_FREQUENCY}(s)."
                sleep $RETRY_FREQUENCY
        done
        ;;
test)
        report
        [ $? -lt 2 ] && write_log "test passed." && exit 0
        write_log "test failed." && exit -1
        ;;
dev)
        ping
        ;;
esac
